kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: gcp-filestore-csi-controller
  namespace: gcp-filestore-csi-driver
spec:
  serviceName: "gcp-filestore-csi-driver"
  replicas: 1
  selector:
    matchLabels:
      app: gcp-filestore-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gcp-filestore-csi-driver
    spec:
      serviceAccount: gcp-filestore-csi-controller-sa
      containers:
        - name: csi-external-attacher
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-attacher:v0.3.0
          args:
            - "--v=999"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: GLOG_logtostderr
              value: "1"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-provisioner:v0.3.0
          args:
            - "--v=999"
            # Remove when https://github.com/kubernetes-csi/external-provisioner/issues/108 is fixed
            - "--provisioner=com.google.csi.filestore"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: GLOG_logtostderr
              value: "1"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: gcp-filestore-driver
          imagePullPolicy: Always
          image: gcr.io/google-containers/volume-csi/gcp-filestore-csi-driver:v0.1.0
          args:
            - "--v=999"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--controller=true"
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/cloud_sa/gcp_filestore_csi_driver_sa.json"
            - name: GLOG_logtostderr
              value: "1"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: cloud-sa-volume
              readOnly: true
              mountPath: "/etc/cloud_sa"
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloud-sa-volume
          secret:
            secretName: gcp-filestore-csi-driver-sa
